"""add delivered_at to orders

Revision ID: 0741f2a57a9d
Revises: '0d91b10f0e61'
Create Date: 2026-07-10 22:16:18.129807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0741f2a57a9d'
down_revision: Union[str, None] = '0d91b10f0e61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('stationary', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stationary', sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('orders', 'delivered_at')
    # ### end Alembic commands ###
